# Generated by Django 3.2.2 on 2021-05-13 09:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='soccerteam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Team', models.CharField(max_length=200)),
                ('Member', models.CharField(max_length=100)),
                ('want_meetting_day', models.DateField()),
                ('What_you_want_to_say', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='blog',
            name='loc',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
